console.log('Git Session Sample Push')
console.log('Git Session Sample Pull')
console.log('One more push GIT session')
console.log('One more Push')
console.log('Using Git commands')
console.log('Using GIT commands trial 2')
